[project]
name = "rst2pdf-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "furo>=2024.8.6",
    "rst2pdf>=0.102",
    "sphinx-copybutton>=0.5.2",
    "sphinx-external-toc>=1.0.1",
    "sphinx>=8.1.3",
]
